export const FETCH_DATAS = "FETCH_DATAS";
export const GET_APP = "GET_APP";
export const ADD_APP_TO_COLLECTION = "ADD_APP_TO_COLLECTION";
export const REMOVE_APP_TO_COLLECTION = "REMOVE_APP_TO_COLLECTION";
export const GET_APP_FAILED = "GET_APP_FAILED";