version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env.development
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moi
      POSTGRES_DB: thecat
    ports: 
      - "5433:5432"
    volumes:
      - ./server/sql/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3005"
    env_file:
      - ./server/.env.development
    depends_on:
      - db