version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "8100:80"
    env_file:
      - ./client/.env.production
    volumes:
      - ./client/public/uploads:/usr/share/nginx/html/uploads
    image: ${DOCKER_USERNAME}/miaw-front:latest
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - ./server/sql/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3005:3005"
    env_file:
      - ./server/.env.production
    volumes:
      - ./server/public/uploads:/app/public/uploads
    depends_on:
      - db
    image: ${DOCKER_USERNAME}/miaw-back:latest
