export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_FIRST_STEP_SUCCESS = "REGISTER_FIRST_STEP_SUCCESS";
export const REGISTER_SECOND_STEP_SUCCESS = "REGISTER_SECOND_STEP_SUCCESS";
export const REGISTER_THIRD_STEP_SUCCESS = "REGISTER_THIRD_STEP_SUCCESS";